### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jsonmat** [cbpowell/MarqueeLabel-Swift#11]
I run the code sample with no problem or error. But when I integrate MarqueeLabel in my app the error below is showing. Kindly help me.

<img width="1653" alt="screen shot 2015-07-20 at 6 14 34 pm" src="https://cloud.githubusercontent.com/assets/4044464/8773984/7c9281ee-2f0b-11e5-8461-512ca4e24f56.png">

**Comment by cbpowell** [comment]
You unfortunately must have pulled from the repo between commits 5e8cc03 and 9ba0901. Commit 5e8cc03 had an error on [line 1158 of MarqueeLabel.swift](https://github.com/cbpowell/MarqueeLabel-Swift/commit/5e8cc03c1bc4b62f0917169eadb55c90451c0897#diff-479baf64c0a9c393f0a8e1153391532eR1158) -- it used `self` instead of `super` inside the `shadowColor` property setter. This causes the infinite loop you see in your trace.

I fixed it in commit 9ba0901, so all you should need to do is pull down the latest changes!

**Comment by cbpowell** [comment]
Whoooops sorry - I reverted commit 9ba0901 with commit cbf9e7f, and then forgot to reapply it! I've just re-fixed it with commit 3c68b5d.
