### ISSUE TITLE
Slow Performance...

### ISSUE THREAD

**Issue by Spacelapp** [cbpowell/MarqueeLabel-Swift#31]
When adding some MarqueeLabels to a UITableViewCell, the performance/UI animation is really bad and slow.

**Comment by cbpowell** [comment]
Yeah - MarqueeLabel depends on Core Animation, and lots of animations in a scrolling table view is generally bad for performance. There are a few changes you can make that will help with scrolling and performance in general when using MarqueeLabel in a table view:
- Set the background color of the label to a totally opaque color, rather than using clear.
- Labelize as much as possible, especially when the table view is scrolling, or at least hold scrolling (not pause!) and reset all the labels to the home position as soon as table view scrolling begins.
- If you can avoid it, don't use edge fades. This allows the view to be totally opaque.

**Comment by cbpowell** [comment]
I meant to note - the Objective-C repo [has a table view demo now](https://github.com/cbpowell/MarqueeLabel/releases/tag/2.5.1). You can take a look at that to see one possible implementation.

**Comment by Spacelapp** [comment]
Well the demo says "TableView coming soon..."
I ended up implementing my own Marquee Label using a scrollview with a timer for auto scroll. Result doesn't have any performance problems :+1:

**Comment by cbpowell** [comment]
Nice! Just trying MarqueeLabel with a fully-opaque background color might get you a significant improvement if you wanted to try that.

And actually I finally got around to implementing the Swift table view demo a few days ago, but haven't pushed it to the master branch yet: https://github.com/cbpowell/MarqueeLabel/tree/combination/MarqueeLabelSwift. It's part of an attempt at combining the Obj-C and Swift repos together.

**Comment by Spacelapp** [comment]
I already tried that, but the performance is still bad on a device :(

**Comment by cbpowell** [comment]
I'll reopen this for now - I'm not sure how much improvement there is to gain within MarqueeLabel itself (since it's really just CAKeyframeAnimations moving the frame), but we can maybe figure out the best practice to get max performance.

Can you describe your configuration? When you say poor performance, do you mean table view scrolling, the label animations, or both?

**Comment by cbpowell** [comment]
Also, poor performance with large font sizes has been [noted before](https://github.com/cbpowell/MarqueeLabel/issues/128).

**Comment by cbpowell** [comment]
Going to close this again for now, since this repo is now fully deprecated in favor of the main MarqueeLabel repo. It sounds like you fixed your specific issue anyway, and I haven't seen any other reports. In general the recommendation stands that you need to minimize in-flight animations while also trying to do table view scrolling!

**Comment by Spacelapp** [comment]
Yes, I fixed it by my own :) thanks anyway! you can close that
