### ISSUE TITLE
No scroll in CustomCell in TableView

### ISSUE THREAD

**Issue by Ondike** [cbpowell/MarqueeLabel-Swift#7]
First, thanks for your code. I have added marquee label in my custom cell in TableView but the scroll doesn't start. Moreover I have an error with the Selector: LabelShouldRestart in the NSNotificationCenter. Do you have a solution for my issue ?

Mathieu

**Comment by Ondike** [comment]
I find a solution:
- Replace UIViewController by UITableViewController in MarqueeLabel.swift
- In tableView function cellForRowAtIndex add this 2 line:
  cell.layoutIfNeeded()
  cell.titleLabel.frame = cell.frame

titleLabel is my MarqueeLabel

It's work great !

**Comment by Ondike** [comment]
Or add "tableView.layoutIfNeeded()" in  viewDidAppear(bool) ;)

**Comment by cbpowell** [comment]
Glad you found a solution! MarqueeLabel can have trouble in UITableViews, because the logic it uses to detect when to automatically scroll doesn't always work with the way views come on-screen (at least in the past). Also you can check out [this note in the Readme](https://github.com/cbpowell/MarqueeLabel#use-in-uitableview-and-uicollectionview) (for the Obj-C version, but just convert it to Swift and it should work just the same). In short, you can put a call to `restartLabel()` in the `willDisplayCell` delegate method.
